# -*- coding: utf-8 -*-
"""R1Py_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0R6SJmRbcmh7V_jwiSvhHxrCGbtkD3F
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install rpy2

# Python code to create a Pandas DataFrame
import pandas as pd
py_df = pd.DataFrame({'x': [1, 2, 3], 'y': [4, 5, 6]})
print("Python DataFrame:")
print(py_df)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext rpy2.ipython
# %%R -i py_df
# # R code to manipulate the DataFrame (input from Python)
# print("R DataFrame:")
# print(py_df)
# py_df$z <- py_df$x + py_df$y
# print("R DataFrame with new column:")
# print(py_df)

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%R
# # Access files from Google Drive
# # Set working directory (adjust path as needed)
# setwd("/content/drive/MyDrive/R_Projects")
# # Load an .Rdata file
# load("my_data.Rdata")
# print(head(my_data))
