# -*- coding: utf-8 -*-
"""R_classification1_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Jn_xTJrpl4rseFpkbjhliMU0ydn5ttq
"""

# Load the rpart package for Decision Trees
library(rpart)

# Load the iris dataset (it's built-in in R)
data(iris)

# Split the data into training and testing sets
# Set a seed for reproducibility
set.seed(123)
train_index <- sample(1:nrow(iris), 0.7 * nrow(iris)) # 70% for training
train_data <- iris[train_index, ]
test_data <- iris[-train_index, ]

# Train a Decision Tree model
# Species ~ . means predict Species using all other variables
dt_model <- rpart(Species ~ ., data = train_data, method = "class")

# Make predictions on the test data
predictions <- predict(dt_model, newdata = test_data, type = "class")

# Evaluate the model's accuracy
accuracy <- sum(predictions == test_data$Species) / nrow(test_data)
print(paste("Accuracy:", round(accuracy, 2)))

# Optional: Visualize the decision tree
# library(rpart.plot)
# rpart.plot(dt_model)

install.packages("rpart.plot")

# Optional: Visualize the decision tree
library(rpart.plot)
rpart.plot(dt_model)

"""Second example: cross-validation"""

# install.packages("caret", dependencies = TRUE)
   install.packages("caret", dependencies = c("Depends", "Suggests"))

library(caret)

# Example: Train a model with caret
    model_fit <- train(
      target_variable ~ .,
      data = training_data,
      method = "glm", # Specify the model engine
      preProcess = c("center", "scale", "nzv"), # Pre-processing steps
      trControl = trainControl(method = "cv", number = 10) # Cross-validation
    )
