# -*- coding: utf-8 -*-
"""R_Text_Classification_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubAuaEyBqjYH8YCueIRBkBXpG1IRHYtj

https://www.kaggle.com/code/evilspirit05/text-classification-in-r-a-practical-approach

https://idc9.github.io/stor390/notes/natural_language_processing/text_classification.html

Using tm (text mining) and e1071 (for Naimve Bayes) packages
This example will classify short text snippets into two categories based on certain kewords.
"""

install.packages("tm")

install.packages("e1071")

library(tm)
library(e1071)

# 1. Create Sample Data
# A data frame with text and their corresponding categories (labels)
data <- data.frame(
 text = c(
   "This is a great movie, I loved it!",
   "The food was terrible, never again.",
   "Excellent service and friendly staff.",
   "Worst experience ever, completely disappointed.",
   "Highly recommend this restaurant.",
   "The film was boring and uninteresting."
 ),
 category = as.factor(c("positive", "negative", "positive", "negative", "positive", "negative"))
)

# 2. Preprocess the Text Data
# Create a corpus from the text data
corpus <- VCorpus(VectorSource(data$text))

# Apply text transformations (e.g., lowercasing, removing punctuation, stopwords)
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, removeWords, stopwords("english"))
corpus <- tm_map(corpus, stripWhitespace)

# Create a Document-Term Matrix (DTM)
dtm <- DocumentTermMatrix(corpus)

# Convert DTM to a data frame for training
dtm_df <- as.data.frame(as.matrix(dtm))

# Add the category labels back to the data frame
dtm_df$category <- data$category

# 3. Train a Classifier (Naive Bayes)
# Split data into training and testing (for simplicity, we'll use all data for training here)
# In a real-world scenario, you would split your data into training and test sets.
model <- naiveBayes(category ~ ., data = dtm_df)

# 4. Make Predictions on New Data
new_text <- c(
 "Amazing experience, definitely coming back!",
 "So bad, waste of time and money."
)

# Preprocess new text similarly
new_corpus <- VCorpus(VectorSource(new_text))
new_corpus <- tm_map(new_corpus, content_transformer(tolower))
new_corpus <- tm_map(new_corpus, removePunctuation)
new_corpus <- tm_map(new_corpus, removeNumbers)
new_corpus <- tm_map(new_corpus, removeWords, stopwords("english"))
new_corpus <- tm_map(new_corpus, stripWhitespace)

# Create DTM for new text, ensuring it has the same features as the training DTM
new_dtm <- DocumentTermMatrix(new_corpus, control = list(dictionary = Terms(dtm)))
new_dtm_df <- as.data.frame(as.matrix(new_dtm))

# Predict the categories for the new text
predictions <- predict(model, newdata = new_dtm_df)

# print(predictions)
print(new_dtm_df)

print(predictions)